extends:
  - "plugin:prettier/recommended"
  - "next/core-web-vitals"
  - "next/typescript"
  - "plugin:@typescript-eslint/stylistic"
rules: {
  "prettier/prettier": "error",
  "@typescript-eslint/no-unused-vars": "off"
}
