name: Template Sync

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - uses: AndreasAugustin/actions-template-sync@v2
        with:
          source_repo_path: zhutmost/analog-blog-starter
          upstream_branch: main
          pr_labels: 'template sync'
